changed the CSS, adding newer photos to the carousel
NateElorreaga/Project1_Group1 pull request #22
Opened 2019-07-01 05:50 UTC by NateElorreaga

Changed up the CSS and working on adding new pics to the page, updated the icons in the navbar.

2019-07-01 18:04 UTC, Droptime24 requested changes

2019-07-01 18:04 UTC, Droptime24 commented on results.html
> -<script src="https://cdn.jsdelivr.net/momentjs/2.12.0/moment.min.js"></script>
We need this link  to the CDN for the time function I added to app.js to work. Did you move it to a new location I'm not seeing?

2019-07-01 18:13 UTC, NateElorreaga commented
Hey - I didn’t move it on purpose. I don’t remember removing it either!
I’ll check when I get home. Or in class with ya!

On Mon, Jul 1, 2019 at 12:04 PM David Luce <notifications@github.com> wrote:

> *@Droptime24* requested changes on this pull request.
> ------------------------------
>
> In results.html
> <https://github.com/NateElorreaga/Project1_Group1/pull/22#discussion_r299156619>
> :
>
> > @@ -17,10 +17,6 @@
>  <link href="https://fonts.googleapis.com/css?family=Alegreya|Alegreya+Sans|Cabin|Inconsolata|Merriweather|Merriweather+Sans|Nunito|Nunito+Sans|Pacifico|Quattrocento|Quattrocento+Sans|Quicksand|Roboto|Roboto+Mono|Roboto+Slab|Rubik|VT323&display=swap <https://fonts.googleapis.com/css?family=Alegreya%7CAlegreya+Sans%7CCabin%7CInconsolata%7CMerriweather%7CMerriweather+Sans%7CNunito%7CNunito+Sans%7CPacifico%7CQuattrocento%7CQuattrocento+Sans%7CQuicksand%7CRoboto%7CRoboto+Mono%7CRoboto+Slab%7CRubik%7CVT323&display=swap>" rel="stylesheet">
>  <link href="https://fonts.googleapis.com/css?family=Iceland&display=swap" rel="stylesheet">
>  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
> -
> -<!-- Momment.js -->
> -<script src="https://cdn.jsdelivr.net/momentjs/2.12.0/moment.min.js"></script>
>
> We need this link to the CDN for the time function I added to app.js to
> work. Did you move it to a new location I'm not seeing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NateElorreaga/Project1_Group1/pull/22?email_source=notifications&email_token=ALEY3VGVLEMLDIDV5Y5LCU3P5JBJPA5CNFSM4H4O4GF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5E2FAI#pullrequestreview-256483969>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALEY3VABXHFVSPAUGXOM3R3P5JBJPANCNFSM4H4O4GFQ>
> .
>

2019-07-01 18:25 UTC, Droptime24 commented
Sounds good man!

On Jul 1, 2019, at 12:13 PM, Nate Elorreaga <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey - I didn’t move it on purpose. I don’t remember removing it either!
I’ll check when I get home. Or in class with ya!

On Mon, Jul 1, 2019 at 12:04 PM David Luce <notifications@github.com<mailto:notifications@github.com>> wrote:

> *@Droptime24* requested changes on this pull request.
> ------------------------------
>
> In results.html
> <https://github.com/NateElorreaga/Project1_Group1/pull/22#discussion_r299156619>
> :
>
> > @@ -17,10 +17,6 @@
> <link href="https://fonts.googleapis.com/css?family=Alegreya|Alegreya+Sans|Cabin|Inconsolata|Merriweather|Merriweather+Sans|Nunito|Nunito+Sans|Pacifico|Quattrocento|Quattrocento+Sans|Quicksand|Roboto|Roboto+Mono|Roboto+Slab|Rubik|VT323&display=swap <https://fonts.googleapis.com/css?family=Alegreya%7CAlegreya+Sans%7CCabin%7CInconsolata%7CMerriweather%7CMerriweather+Sans%7CNunito%7CNunito+Sans%7CPacifico%7CQuattrocento%7CQuattrocento+Sans%7CQuicksand%7CRoboto%7CRoboto+Mono%7CRoboto+Slab%7CRubik%7CVT323&display=swap>" rel="stylesheet">
> <link href="https://fonts.googleapis.com/css?family=Iceland&display=swap" rel="stylesheet">
> <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
> -
> -<!-- Momment.js -->
> -<script src="https://cdn.jsdelivr.net/momentjs/2.12.0/moment.min.js"></script>
>
> We need this link to the CDN for the time function I added to app.js to
> work. Did you move it to a new location I'm not seeing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NateElorreaga/Project1_Group1/pull/22?email_source=notifications&email_token=ALEY3VGVLEMLDIDV5Y5LCU3P5JBJPA5CNFSM4H4O4GF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB5E2FAI#pullrequestreview-256483969>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALEY3VABXHFVSPAUGXOM3R3P5JBJPANCNFSM4H4O4GFQ>
> .
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/NateElorreaga/Project1_Group1/pull/22?email_source=notifications&email_token=AJYCWWSFJUZEEWRZSCF563TP5JCNNA5CNFSM4H4O4GF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY65Q2Y#issuecomment-507369579>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AJYCWWQNIVOFHL5VA5UBQF3P5JCNNANCNFSM4H4O4GFQ>.

2019-07-02 01:26 UTC, Droptime24 approved these changes

2019-07-02 01:26 UTC, merged